import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

// Supported languages
export const languages = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
];

// Comprehensive translations
const translations: Record<string, Record<string, string>> = {
  en: {
    "app.name": "Know Deep",
    "app.tagline": "Your All-in-One Smart AI Companion",
    "nav.features": "Features",
    "nav.tools": "Tools",
    "nav.pricing": "Pricing",
    "nav.gallery": "Gallery",
    "nav.dashboard": "Dashboard",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.displayName": "Display Name",
    "auth.country": "Country",
    "auth.language": "Language",
    "auth.welcome": "Welcome back",
    "auth.createAccount": "Create account",
    "auth.noAccount": "Don't have an account? Sign up",
    "auth.hasAccount": "Already have an account? Sign in",
    "auth.logout": "Logout",
    "chat.placeholder": "Type your message...",
    "chat.send": "Send",
    "chat.newChat": "New Chat",
    "chat.conversations": "Conversations",
    "chat.noConversations": "No conversations yet",
    "chat.deleteConfirm": "Delete this conversation?",
    "chat.share": "Share",
    "chat.export": "Export",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.back": "Back",
    "common.next": "Next",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "pricing.title": "Choose Your Plan",
    "pricing.month": "/month",
    "pricing.upgrade": "Upgrade",
    "pricing.free": "Free",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Enterprise",
    "offline.title": "No Internet Connection",
    "offline.message": "Check your connection and try again",
    "offline.retry": "Retry",
    "settings.title": "Settings",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.notifications": "Notifications",
    "settings.profile": "Profile",
    "settings.account": "Account",
    "settings.subscription": "Subscription",
    "tools.imageGenerator": "Image Generator",
    "tools.imageEnhancer": "Image Enhancer",
    "tools.summarizer": "Summarizer",
    "tools.translator": "Translator",
    "tools.voiceAssistant": "Voice Assistant",
    "tools.documentChat": "Document Chat",
    "tools.codeInterpreter": "Code Interpreter",
    "tools.webSearch": "Web Search",
    "tools.homeworkAssistant": "Homework Assistant",
    "tools.appCreator": "App Creator",
    "news.title": "News Feed",
    "news.readAloud": "Read Aloud",
    "news.bookmark": "Bookmark",
    "news.share": "Share",
    "news.categories": "Categories",
    "profile.title": "Profile",
    "profile.editProfile": "Edit Profile",
    "profile.changeAvatar": "Change Avatar",
  },
  hi: {
    "app.name": "Know Deep",
    "app.tagline": "आपका ऑल-इन-वन स्मार्ट AI साथी",
    "nav.features": "विशेषताएं",
    "nav.tools": "उपकरण",
    "nav.pricing": "मूल्य निर्धारण",
    "nav.gallery": "गैलरी",
    "nav.dashboard": "डैशबोर्ड",
    "auth.signIn": "साइन इन करें",
    "auth.signUp": "साइन अप करें",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.displayName": "प्रदर्शन नाम",
    "auth.country": "देश",
    "auth.language": "भाषा",
    "auth.welcome": "वापसी पर स्वागत है",
    "auth.createAccount": "खाता बनाएं",
    "auth.noAccount": "खाता नहीं है? साइन अप करें",
    "auth.hasAccount": "पहले से खाता है? साइन इन करें",
    "auth.logout": "लॉग आउट",
    "chat.placeholder": "अपना संदेश टाइप करें...",
    "chat.send": "भेजें",
    "chat.newChat": "नई चैट",
    "chat.conversations": "वार्तालाप",
    "chat.noConversations": "अभी तक कोई वार्तालाप नहीं",
    "chat.deleteConfirm": "इस वार्तालाप को हटाएं?",
    "chat.share": "शेयर करें",
    "chat.export": "निर्यात करें",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफलता",
    "common.cancel": "रद्द करें",
    "common.save": "सहेजें",
    "common.delete": "हटाएं",
    "common.edit": "संपादित करें",
    "common.search": "खोजें",
    "common.back": "वापस",
    "common.next": "आगे",
    "common.confirm": "पुष्टि करें",
    "common.close": "बंद करें",
    "pricing.title": "अपनी योजना चुनें",
    "pricing.month": "/महीना",
    "pricing.upgrade": "अपग्रेड करें",
    "pricing.free": "मुफ्त",
    "pricing.pro": "प्रो",
    "pricing.enterprise": "एंटरप्राइज",
    "offline.title": "इंटरनेट कनेक्शन नहीं",
    "offline.message": "अपना कनेक्शन जांचें और पुनः प्रयास करें",
    "offline.retry": "पुनः प्रयास करें",
    "settings.title": "सेटिंग्स",
    "settings.language": "भाषा",
    "settings.theme": "थीम",
    "settings.notifications": "सूचनाएं",
    "settings.profile": "प्रोफाइल",
    "settings.account": "खाता",
    "settings.subscription": "सदस्यता",
    "tools.imageGenerator": "इमेज जनरेटर",
    "tools.imageEnhancer": "इमेज एन्हांसर",
    "tools.summarizer": "सारांशकर्ता",
    "tools.translator": "अनुवादक",
    "tools.voiceAssistant": "वॉइस असिस्टेंट",
    "tools.documentChat": "दस्तावेज़ चैट",
    "tools.codeInterpreter": "कोड इंटरप्रेटर",
    "tools.webSearch": "वेब खोज",
    "tools.homeworkAssistant": "होमवर्क असिस्टेंट",
    "tools.appCreator": "ऐप क्रिएटर",
    "news.title": "समाचार फ़ीड",
    "news.readAloud": "पढ़कर सुनाएं",
    "news.bookmark": "बुकमार्क",
    "news.share": "शेयर करें",
    "news.categories": "श्रेणियां",
    "profile.title": "प्रोफाइल",
    "profile.editProfile": "प्रोफाइल संपादित करें",
    "profile.changeAvatar": "अवतार बदलें",
  },
  bn: {
    "app.name": "Know Deep",
    "app.tagline": "আপনার অল-ইন-ওয়ান স্মার্ট AI সঙ্গী",
    "nav.features": "বৈশিষ্ট্য",
    "nav.tools": "সরঞ্জাম",
    "nav.pricing": "মূল্য",
    "nav.gallery": "গ্যালারি",
    "nav.dashboard": "ড্যাশবোর্ড",
    "auth.signIn": "সাইন ইন করুন",
    "auth.signUp": "সাইন আপ করুন",
    "auth.email": "ইমেল",
    "auth.password": "পাসওয়ার্ড",
    "auth.displayName": "প্রদর্শন নাম",
    "auth.country": "দেশ",
    "auth.language": "ভাষা",
    "auth.welcome": "স্বাগতম",
    "auth.createAccount": "অ্যাকাউন্ট তৈরি করুন",
    "auth.noAccount": "অ্যাকাউন্ট নেই? সাইন আপ করুন",
    "auth.hasAccount": "অ্যাকাউন্ট আছে? সাইন ইন করুন",
    "auth.logout": "লগ আউট",
    "chat.placeholder": "আপনার বার্তা টাইপ করুন...",
    "chat.send": "পাঠান",
    "chat.newChat": "নতুন চ্যাট",
    "chat.conversations": "কথোপকথন",
    "chat.noConversations": "এখনও কোনো কথোপকথন নেই",
    "chat.deleteConfirm": "এই কথোপকথন মুছে ফেলবেন?",
    "chat.share": "শেয়ার করুন",
    "chat.export": "রপ্তানি করুন",
    "common.loading": "লোড হচ্ছে...",
    "common.error": "ত্রুটি",
    "common.success": "সফল",
    "common.cancel": "বাতিল",
    "common.save": "সংরক্ষণ করুন",
    "common.delete": "মুছুন",
    "common.edit": "সম্পাদনা করুন",
    "common.search": "অনুসন্ধান করুন",
    "common.back": "ফিরে যান",
    "common.next": "পরবর্তী",
    "common.confirm": "নিশ্চিত করুন",
    "common.close": "বন্ধ করুন",
    "pricing.title": "আপনার প্ল্যান বেছে নিন",
    "pricing.month": "/মাস",
    "pricing.upgrade": "আপগ্রেড করুন",
    "pricing.free": "বিনামূল্যে",
    "pricing.pro": "প্রো",
    "pricing.enterprise": "এন্টারপ্রাইজ",
    "offline.title": "ইন্টারনেট সংযোগ নেই",
    "offline.message": "আপনার সংযোগ পরীক্ষা করুন এবং আবার চেষ্টা করুন",
    "offline.retry": "পুনরায় চেষ্টা করুন",
    "settings.title": "সেটিংস",
    "settings.language": "ভাষা",
    "settings.theme": "থিম",
    "settings.notifications": "বিজ্ঞপ্তি",
    "settings.profile": "প্রোফাইল",
    "settings.account": "অ্যাকাউন্ট",
    "settings.subscription": "সাবস্ক্রিপশন",
    "tools.imageGenerator": "ইমেজ জেনারেটর",
    "tools.imageEnhancer": "ইমেজ এনহ্যান্সার",
    "tools.summarizer": "সারসংক্ষেপকারী",
    "tools.translator": "অনুবাদক",
    "tools.voiceAssistant": "ভয়েস অ্যাসিস্ট্যান্ট",
    "tools.documentChat": "ডকুমেন্ট চ্যাট",
    "tools.codeInterpreter": "কোড ইন্টারপ্রেটার",
    "tools.webSearch": "ওয়েব সার্চ",
    "tools.homeworkAssistant": "হোমওয়ার্ক অ্যাসিস্ট্যান্ট",
    "tools.appCreator": "অ্যাপ ক্রিয়েটর",
    "news.title": "নিউজ ফিড",
    "news.readAloud": "পড়ে শোনান",
    "news.bookmark": "বুকমার্ক",
    "news.share": "শেয়ার করুন",
    "news.categories": "ক্যাটাগরি",
    "profile.title": "প্রোফাইল",
    "profile.editProfile": "প্রোফাইল সম্পাদনা করুন",
    "profile.changeAvatar": "অবতার পরিবর্তন করুন",
  },
  es: {
    "app.name": "Know Deep",
    "app.tagline": "Tu compañero de IA inteligente todo en uno",
    "nav.features": "Características",
    "nav.tools": "Herramientas",
    "nav.pricing": "Precios",
    "nav.gallery": "Galería",
    "nav.dashboard": "Panel",
    "auth.signIn": "Iniciar sesión",
    "auth.signUp": "Registrarse",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña",
    "auth.displayName": "Nombre para mostrar",
    "auth.country": "País",
    "auth.language": "Idioma",
    "auth.welcome": "Bienvenido de nuevo",
    "auth.createAccount": "Crear cuenta",
    "auth.noAccount": "¿No tienes cuenta? Regístrate",
    "auth.hasAccount": "¿Ya tienes cuenta? Inicia sesión",
    "auth.logout": "Cerrar sesión",
    "chat.placeholder": "Escribe tu mensaje...",
    "chat.send": "Enviar",
    "chat.newChat": "Nuevo chat",
    "chat.conversations": "Conversaciones",
    "chat.noConversations": "Aún no hay conversaciones",
    "chat.deleteConfirm": "¿Eliminar esta conversación?",
    "chat.share": "Compartir",
    "chat.export": "Exportar",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.search": "Buscar",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.confirm": "Confirmar",
    "common.close": "Cerrar",
    "pricing.title": "Elige tu plan",
    "pricing.month": "/mes",
    "pricing.upgrade": "Mejorar",
    "pricing.free": "Gratis",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Empresa",
    "offline.title": "Sin conexión a internet",
    "offline.message": "Verifica tu conexión e intenta de nuevo",
    "offline.retry": "Reintentar",
    "settings.title": "Configuración",
    "settings.language": "Idioma",
    "settings.theme": "Tema",
    "settings.notifications": "Notificaciones",
    "settings.profile": "Perfil",
    "settings.account": "Cuenta",
    "settings.subscription": "Suscripción",
    "tools.imageGenerator": "Generador de imágenes",
    "tools.imageEnhancer": "Mejorador de imágenes",
    "tools.summarizer": "Resumidor",
    "tools.translator": "Traductor",
    "tools.voiceAssistant": "Asistente de voz",
    "tools.documentChat": "Chat de documentos",
    "tools.codeInterpreter": "Intérprete de código",
    "tools.webSearch": "Búsqueda web",
    "tools.homeworkAssistant": "Asistente de tareas",
    "tools.appCreator": "Creador de apps",
    "news.title": "Noticias",
    "news.readAloud": "Leer en voz alta",
    "news.bookmark": "Marcador",
    "news.share": "Compartir",
    "news.categories": "Categorías",
    "profile.title": "Perfil",
    "profile.editProfile": "Editar perfil",
    "profile.changeAvatar": "Cambiar avatar",
  },
  fr: {
    "app.name": "Know Deep",
    "app.tagline": "Votre compagnon IA intelligent tout-en-un",
    "nav.features": "Fonctionnalités",
    "nav.tools": "Outils",
    "nav.pricing": "Tarifs",
    "nav.gallery": "Galerie",
    "nav.dashboard": "Tableau de bord",
    "auth.signIn": "Se connecter",
    "auth.signUp": "S'inscrire",
    "auth.email": "E-mail",
    "auth.password": "Mot de passe",
    "auth.displayName": "Nom d'affichage",
    "auth.country": "Pays",
    "auth.language": "Langue",
    "auth.welcome": "Bon retour",
    "auth.createAccount": "Créer un compte",
    "auth.noAccount": "Pas de compte ? Inscrivez-vous",
    "auth.hasAccount": "Déjà un compte ? Connectez-vous",
    "auth.logout": "Déconnexion",
    "chat.placeholder": "Tapez votre message...",
    "chat.send": "Envoyer",
    "chat.newChat": "Nouveau chat",
    "chat.conversations": "Conversations",
    "chat.noConversations": "Pas encore de conversations",
    "chat.deleteConfirm": "Supprimer cette conversation ?",
    "chat.share": "Partager",
    "chat.export": "Exporter",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.search": "Rechercher",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.confirm": "Confirmer",
    "common.close": "Fermer",
    "pricing.title": "Choisissez votre plan",
    "pricing.month": "/mois",
    "pricing.upgrade": "Mettre à niveau",
    "pricing.free": "Gratuit",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Entreprise",
    "offline.title": "Pas de connexion Internet",
    "offline.message": "Vérifiez votre connexion et réessayez",
    "offline.retry": "Réessayer",
    "settings.title": "Paramètres",
    "settings.language": "Langue",
    "settings.theme": "Thème",
    "settings.notifications": "Notifications",
    "settings.profile": "Profil",
    "settings.account": "Compte",
    "settings.subscription": "Abonnement",
    "tools.imageGenerator": "Générateur d'images",
    "tools.imageEnhancer": "Améliorateur d'images",
    "tools.summarizer": "Résumeur",
    "tools.translator": "Traducteur",
    "tools.voiceAssistant": "Assistant vocal",
    "tools.documentChat": "Chat document",
    "tools.codeInterpreter": "Interpréteur de code",
    "tools.webSearch": "Recherche web",
    "tools.homeworkAssistant": "Assistant devoirs",
    "tools.appCreator": "Créateur d'apps",
    "news.title": "Fil d'actualités",
    "news.readAloud": "Lire à haute voix",
    "news.bookmark": "Favori",
    "news.share": "Partager",
    "news.categories": "Catégories",
    "profile.title": "Profil",
    "profile.editProfile": "Modifier le profil",
    "profile.changeAvatar": "Changer l'avatar",
  },
  de: {
    "app.name": "Know Deep",
    "app.tagline": "Ihr All-in-One intelligenter KI-Begleiter",
    "nav.features": "Funktionen",
    "nav.tools": "Werkzeuge",
    "nav.pricing": "Preise",
    "nav.gallery": "Galerie",
    "nav.dashboard": "Dashboard",
    "auth.signIn": "Anmelden",
    "auth.signUp": "Registrieren",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.displayName": "Anzeigename",
    "auth.country": "Land",
    "auth.language": "Sprache",
    "auth.welcome": "Willkommen zurück",
    "auth.createAccount": "Konto erstellen",
    "auth.noAccount": "Kein Konto? Registrieren",
    "auth.hasAccount": "Bereits ein Konto? Anmelden",
    "auth.logout": "Abmelden",
    "chat.placeholder": "Nachricht eingeben...",
    "chat.send": "Senden",
    "chat.newChat": "Neuer Chat",
    "chat.conversations": "Unterhaltungen",
    "chat.noConversations": "Noch keine Unterhaltungen",
    "chat.deleteConfirm": "Diese Unterhaltung löschen?",
    "chat.share": "Teilen",
    "chat.export": "Exportieren",
    "common.loading": "Lädt...",
    "common.error": "Fehler",
    "common.success": "Erfolg",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.search": "Suchen",
    "common.back": "Zurück",
    "common.next": "Weiter",
    "common.confirm": "Bestätigen",
    "common.close": "Schließen",
    "pricing.title": "Wählen Sie Ihren Plan",
    "pricing.month": "/Monat",
    "pricing.upgrade": "Upgrade",
    "pricing.free": "Kostenlos",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Unternehmen",
    "offline.title": "Keine Internetverbindung",
    "offline.message": "Überprüfen Sie Ihre Verbindung und versuchen Sie es erneut",
    "offline.retry": "Erneut versuchen",
    "settings.title": "Einstellungen",
    "settings.language": "Sprache",
    "settings.theme": "Design",
    "settings.notifications": "Benachrichtigungen",
    "settings.profile": "Profil",
    "settings.account": "Konto",
    "settings.subscription": "Abonnement",
    "tools.imageGenerator": "Bildgenerator",
    "tools.imageEnhancer": "Bildverbesserer",
    "tools.summarizer": "Zusammenfasser",
    "tools.translator": "Übersetzer",
    "tools.voiceAssistant": "Sprachassistent",
    "tools.documentChat": "Dokument-Chat",
    "tools.codeInterpreter": "Code-Interpreter",
    "tools.webSearch": "Websuche",
    "tools.homeworkAssistant": "Hausaufgaben-Assistent",
    "tools.appCreator": "App-Ersteller",
    "news.title": "Nachrichten-Feed",
    "news.readAloud": "Vorlesen",
    "news.bookmark": "Lesezeichen",
    "news.share": "Teilen",
    "news.categories": "Kategorien",
    "profile.title": "Profil",
    "profile.editProfile": "Profil bearbeiten",
    "profile.changeAvatar": "Avatar ändern",
  },
  ja: {
    "app.name": "Know Deep",
    "app.tagline": "オールインワンのスマートAIコンパニオン",
    "nav.features": "機能",
    "nav.tools": "ツール",
    "nav.pricing": "料金",
    "nav.gallery": "ギャラリー",
    "nav.dashboard": "ダッシュボード",
    "auth.signIn": "サインイン",
    "auth.signUp": "サインアップ",
    "auth.email": "メール",
    "auth.password": "パスワード",
    "auth.displayName": "表示名",
    "auth.country": "国",
    "auth.language": "言語",
    "auth.welcome": "おかえりなさい",
    "auth.createAccount": "アカウント作成",
    "auth.noAccount": "アカウントをお持ちでないですか？サインアップ",
    "auth.hasAccount": "すでにアカウントをお持ちですか？サインイン",
    "auth.logout": "ログアウト",
    "chat.placeholder": "メッセージを入力...",
    "chat.send": "送信",
    "chat.newChat": "新しいチャット",
    "chat.conversations": "会話",
    "chat.noConversations": "まだ会話がありません",
    "chat.deleteConfirm": "この会話を削除しますか？",
    "chat.share": "共有",
    "chat.export": "エクスポート",
    "common.loading": "読み込み中...",
    "common.error": "エラー",
    "common.success": "成功",
    "common.cancel": "キャンセル",
    "common.save": "保存",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.search": "検索",
    "common.back": "戻る",
    "common.next": "次へ",
    "common.confirm": "確認",
    "common.close": "閉じる",
    "pricing.title": "プランを選択",
    "pricing.month": "/月",
    "pricing.upgrade": "アップグレード",
    "pricing.free": "無料",
    "pricing.pro": "プロ",
    "pricing.enterprise": "エンタープライズ",
    "offline.title": "インターネット接続なし",
    "offline.message": "接続を確認して再試行してください",
    "offline.retry": "再試行",
    "settings.title": "設定",
    "settings.language": "言語",
    "settings.theme": "テーマ",
    "settings.notifications": "通知",
    "settings.profile": "プロフィール",
    "settings.account": "アカウント",
    "settings.subscription": "サブスクリプション",
    "tools.imageGenerator": "画像生成",
    "tools.imageEnhancer": "画像強化",
    "tools.summarizer": "要約",
    "tools.translator": "翻訳",
    "tools.voiceAssistant": "音声アシスタント",
    "tools.documentChat": "ドキュメントチャット",
    "tools.codeInterpreter": "コードインタープリター",
    "tools.webSearch": "ウェブ検索",
    "tools.homeworkAssistant": "宿題アシスタント",
    "tools.appCreator": "アプリ作成",
    "news.title": "ニュースフィード",
    "news.readAloud": "読み上げ",
    "news.bookmark": "ブックマーク",
    "news.share": "共有",
    "news.categories": "カテゴリ",
    "profile.title": "プロフィール",
    "profile.editProfile": "プロフィールを編集",
    "profile.changeAvatar": "アバターを変更",
  },
  zh: {
    "app.name": "Know Deep",
    "app.tagline": "您的一站式智能AI伙伴",
    "nav.features": "功能",
    "nav.tools": "工具",
    "nav.pricing": "定价",
    "nav.gallery": "画廊",
    "nav.dashboard": "仪表板",
    "auth.signIn": "登录",
    "auth.signUp": "注册",
    "auth.email": "电子邮件",
    "auth.password": "密码",
    "auth.displayName": "显示名称",
    "auth.country": "国家",
    "auth.language": "语言",
    "auth.welcome": "欢迎回来",
    "auth.createAccount": "创建账户",
    "auth.noAccount": "没有账户？注册",
    "auth.hasAccount": "已有账户？登录",
    "auth.logout": "退出登录",
    "chat.placeholder": "输入您的消息...",
    "chat.send": "发送",
    "chat.newChat": "新对话",
    "chat.conversations": "对话",
    "chat.noConversations": "暂无对话",
    "chat.deleteConfirm": "删除此对话？",
    "chat.share": "分享",
    "chat.export": "导出",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.search": "搜索",
    "common.back": "返回",
    "common.next": "下一步",
    "common.confirm": "确认",
    "common.close": "关闭",
    "pricing.title": "选择您的计划",
    "pricing.month": "/月",
    "pricing.upgrade": "升级",
    "pricing.free": "免费",
    "pricing.pro": "专业版",
    "pricing.enterprise": "企业版",
    "offline.title": "无网络连接",
    "offline.message": "请检查您的连接并重试",
    "offline.retry": "重试",
    "settings.title": "设置",
    "settings.language": "语言",
    "settings.theme": "主题",
    "settings.notifications": "通知",
    "settings.profile": "个人资料",
    "settings.account": "账户",
    "settings.subscription": "订阅",
    "tools.imageGenerator": "图像生成器",
    "tools.imageEnhancer": "图像增强器",
    "tools.summarizer": "摘要器",
    "tools.translator": "翻译器",
    "tools.voiceAssistant": "语音助手",
    "tools.documentChat": "文档对话",
    "tools.codeInterpreter": "代码解释器",
    "tools.webSearch": "网页搜索",
    "tools.homeworkAssistant": "作业助手",
    "tools.appCreator": "应用创建器",
    "news.title": "新闻订阅",
    "news.readAloud": "朗读",
    "news.bookmark": "书签",
    "news.share": "分享",
    "news.categories": "分类",
    "profile.title": "个人资料",
    "profile.editProfile": "编辑个人资料",
    "profile.changeAvatar": "更换头像",
  },
  ar: {
    "app.name": "Know Deep",
    "app.tagline": "رفيقك الذكي الشامل للذكاء الاصطناعي",
    "nav.features": "الميزات",
    "nav.tools": "الأدوات",
    "nav.pricing": "الأسعار",
    "nav.gallery": "المعرض",
    "nav.dashboard": "لوحة التحكم",
    "auth.signIn": "تسجيل الدخول",
    "auth.signUp": "إنشاء حساب",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.displayName": "اسم العرض",
    "auth.country": "البلد",
    "auth.language": "اللغة",
    "auth.welcome": "مرحباً بعودتك",
    "auth.createAccount": "إنشاء حساب",
    "auth.noAccount": "ليس لديك حساب؟ سجل الآن",
    "auth.hasAccount": "لديك حساب بالفعل؟ سجل الدخول",
    "auth.logout": "تسجيل الخروج",
    "chat.placeholder": "اكتب رسالتك...",
    "chat.send": "إرسال",
    "chat.newChat": "محادثة جديدة",
    "chat.conversations": "المحادثات",
    "chat.noConversations": "لا توجد محادثات بعد",
    "chat.deleteConfirm": "حذف هذه المحادثة؟",
    "chat.share": "مشاركة",
    "chat.export": "تصدير",
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.success": "نجاح",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.search": "بحث",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.confirm": "تأكيد",
    "common.close": "إغلاق",
    "pricing.title": "اختر خطتك",
    "pricing.month": "/شهر",
    "pricing.upgrade": "ترقية",
    "pricing.free": "مجاني",
    "pricing.pro": "برو",
    "pricing.enterprise": "المؤسسات",
    "offline.title": "لا يوجد اتصال بالإنترنت",
    "offline.message": "تحقق من اتصالك وحاول مرة أخرى",
    "offline.retry": "إعادة المحاولة",
    "settings.title": "الإعدادات",
    "settings.language": "اللغة",
    "settings.theme": "المظهر",
    "settings.notifications": "الإشعارات",
    "settings.profile": "الملف الشخصي",
    "settings.account": "الحساب",
    "settings.subscription": "الاشتراك",
    "tools.imageGenerator": "منشئ الصور",
    "tools.imageEnhancer": "محسن الصور",
    "tools.summarizer": "الملخص",
    "tools.translator": "المترجم",
    "tools.voiceAssistant": "المساعد الصوتي",
    "tools.documentChat": "محادثة المستندات",
    "tools.codeInterpreter": "مفسر الكود",
    "tools.webSearch": "البحث على الويب",
    "tools.homeworkAssistant": "مساعد الواجبات",
    "tools.appCreator": "منشئ التطبيقات",
    "news.title": "آخر الأخبار",
    "news.readAloud": "القراءة بصوت عالٍ",
    "news.bookmark": "إشارة مرجعية",
    "news.share": "مشاركة",
    "news.categories": "الفئات",
    "profile.title": "الملف الشخصي",
    "profile.editProfile": "تعديل الملف الشخصي",
    "profile.changeAvatar": "تغيير الصورة الرمزية",
  },
  te: {
    "app.name": "Know Deep",
    "app.tagline": "మీ ఆల్-ఇన్-వన్ స్మార్ట్ AI సహచరుడు",
    "nav.features": "ఫీచర్లు",
    "nav.tools": "టూల్స్",
    "nav.pricing": "ధర",
    "nav.gallery": "గ్యాలరీ",
    "nav.dashboard": "డాష్‌బోర్డ్",
    "auth.signIn": "సైన్ ఇన్",
    "auth.signUp": "సైన్ అప్",
    "auth.email": "ఇమెయిల్",
    "auth.password": "పాస్‌వర్డ్",
    "auth.displayName": "ప్రదర్శన పేరు",
    "auth.country": "దేశం",
    "auth.language": "భాష",
    "auth.welcome": "మళ్ళీ స్వాగతం",
    "auth.createAccount": "ఖాతా సృష్టించండి",
    "auth.noAccount": "ఖాతా లేదా? సైన్ అప్ చేయండి",
    "auth.hasAccount": "ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి",
    "auth.logout": "లాగ్ అవుట్",
    "chat.placeholder": "మీ సందేశాన్ని టైప్ చేయండి...",
    "chat.send": "పంపండి",
    "chat.newChat": "కొత్త చాట్",
    "common.loading": "లోడ్ అవుతోంది...",
    "common.error": "లోపం",
    "common.success": "విజయం",
    "common.cancel": "రద్దు చేయండి",
    "common.save": "సేవ్ చేయండి",
    "common.delete": "తొలగించు",
    "common.edit": "సవరించు",
    "common.search": "వెతకండి",
    "pricing.title": "మీ ప్లాన్‌ని ఎంచుకోండి",
    "pricing.month": "/నెల",
    "pricing.upgrade": "అప్‌గ్రేడ్",
    "offline.title": "ఇంటర్నెట్ కనెక్షన్ లేదు",
    "offline.message": "మీ కనెక్షన్ తనిఖీ చేసి మళ్ళీ ప్రయత్నించండి",
    "offline.retry": "మళ్ళీ ప్రయత్నించండి",
    "settings.title": "సెట్టింగ్‌లు",
    "settings.language": "భాష",
  },
  mr: {
    "app.name": "Know Deep",
    "app.tagline": "तुमचा ऑल-इन-वन स्मार्ट AI साथी",
    "nav.features": "वैशिष्ट्ये",
    "nav.tools": "साधने",
    "nav.pricing": "किंमत",
    "nav.gallery": "गॅलरी",
    "nav.dashboard": "डॅशबोर्ड",
    "auth.signIn": "साइन इन करा",
    "auth.signUp": "साइन अप करा",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.displayName": "प्रदर्शन नाव",
    "auth.country": "देश",
    "auth.language": "भाषा",
    "auth.welcome": "पुन्हा स्वागत आहे",
    "auth.createAccount": "खाते तयार करा",
    "auth.noAccount": "खाते नाही? साइन अप करा",
    "auth.hasAccount": "आधीच खाते आहे? साइन इन करा",
    "auth.logout": "लॉग आउट",
    "chat.placeholder": "तुमचा संदेश टाइप करा...",
    "chat.send": "पाठवा",
    "chat.newChat": "नवीन चॅट",
    "common.loading": "लोड होत आहे...",
    "common.error": "त्रुटी",
    "common.success": "यश",
    "common.cancel": "रद्द करा",
    "common.save": "जतन करा",
    "common.delete": "हटवा",
    "common.edit": "संपादित करा",
    "common.search": "शोधा",
    "pricing.title": "तुमची योजना निवडा",
    "pricing.month": "/महिना",
    "pricing.upgrade": "अपग्रेड करा",
    "offline.title": "इंटरनेट कनेक्शन नाही",
    "offline.message": "तुमचे कनेक्शन तपासा आणि पुन्हा प्रयत्न करा",
    "offline.retry": "पुन्हा प्रयत्न करा",
    "settings.title": "सेटिंग्ज",
    "settings.language": "भाषा",
  },
  ta: {
    "app.name": "Know Deep",
    "app.tagline": "உங்கள் ஆல்-இன்-ஒன் ஸ்மார்ட் AI துணை",
    "nav.features": "அம்சங்கள்",
    "nav.tools": "கருவிகள்",
    "nav.pricing": "விலை",
    "nav.gallery": "கேலரி",
    "nav.dashboard": "டாஷ்போர்டு",
    "auth.signIn": "உள்நுழையவும்",
    "auth.signUp": "பதிவு செய்யவும்",
    "auth.email": "மின்னஞ்சல்",
    "auth.password": "கடவுச்சொல்",
    "auth.displayName": "காட்சிப் பெயர்",
    "auth.country": "நாடு",
    "auth.language": "மொழி",
    "auth.welcome": "மீண்டும் வரவேற்கிறோம்",
    "auth.createAccount": "கணக்கை உருவாக்கவும்",
    "auth.noAccount": "கணக்கு இல்லையா? பதிவு செய்யவும்",
    "auth.hasAccount": "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையவும்",
    "auth.logout": "வெளியேறு",
    "chat.placeholder": "உங்கள் செய்தியை தட்டச்சு செய்யவும்...",
    "chat.send": "அனுப்பு",
    "chat.newChat": "புதிய அரட்டை",
    "common.loading": "ஏற்றுகிறது...",
    "common.error": "பிழை",
    "common.success": "வெற்றி",
    "common.cancel": "ரத்து செய்",
    "common.save": "சேமி",
    "common.delete": "நீக்கு",
    "common.edit": "திருத்து",
    "common.search": "தேடு",
    "pricing.title": "உங்கள் திட்டத்தைத் தேர்ந்தெடுக்கவும்",
    "pricing.month": "/மாதம்",
    "pricing.upgrade": "மேம்படுத்து",
    "offline.title": "இணைய இணைப்பு இல்லை",
    "offline.message": "உங்கள் இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்",
    "offline.retry": "மீண்டும் முயற்சிக்கவும்",
    "settings.title": "அமைப்புகள்",
    "settings.language": "மொழி",
  },
  pt: {
    "app.name": "Know Deep",
    "app.tagline": "Seu companheiro de IA inteligente tudo-em-um",
    "nav.features": "Recursos",
    "nav.tools": "Ferramentas",
    "nav.pricing": "Preços",
    "nav.gallery": "Galeria",
    "nav.dashboard": "Painel",
    "auth.signIn": "Entrar",
    "auth.signUp": "Cadastrar",
    "auth.email": "E-mail",
    "auth.password": "Senha",
    "auth.displayName": "Nome de exibição",
    "auth.country": "País",
    "auth.language": "Idioma",
    "auth.welcome": "Bem-vindo de volta",
    "auth.createAccount": "Criar conta",
    "auth.noAccount": "Não tem conta? Cadastre-se",
    "auth.hasAccount": "Já tem conta? Entre",
    "auth.logout": "Sair",
    "chat.placeholder": "Digite sua mensagem...",
    "chat.send": "Enviar",
    "chat.newChat": "Novo chat",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.cancel": "Cancelar",
    "common.save": "Salvar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.search": "Pesquisar",
    "pricing.title": "Escolha seu plano",
    "pricing.month": "/mês",
    "pricing.upgrade": "Atualizar",
    "offline.title": "Sem conexão com a Internet",
    "offline.message": "Verifique sua conexão e tente novamente",
    "offline.retry": "Tentar novamente",
    "settings.title": "Configurações",
    "settings.language": "Idioma",
  },
  ru: {
    "app.name": "Know Deep",
    "app.tagline": "Ваш универсальный умный ИИ-компаньон",
    "nav.features": "Возможности",
    "nav.tools": "Инструменты",
    "nav.pricing": "Цены",
    "nav.gallery": "Галерея",
    "nav.dashboard": "Панель",
    "auth.signIn": "Войти",
    "auth.signUp": "Регистрация",
    "auth.email": "Эл. почта",
    "auth.password": "Пароль",
    "auth.displayName": "Имя пользователя",
    "auth.country": "Страна",
    "auth.language": "Язык",
    "auth.welcome": "С возвращением",
    "auth.createAccount": "Создать аккаунт",
    "auth.noAccount": "Нет аккаунта? Зарегистрируйтесь",
    "auth.hasAccount": "Уже есть аккаунт? Войдите",
    "auth.logout": "Выйти",
    "chat.placeholder": "Введите сообщение...",
    "chat.send": "Отправить",
    "chat.newChat": "Новый чат",
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.success": "Успешно",
    "common.cancel": "Отмена",
    "common.save": "Сохранить",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.search": "Поиск",
    "pricing.title": "Выберите план",
    "pricing.month": "/месяц",
    "pricing.upgrade": "Улучшить",
    "offline.title": "Нет подключения к интернету",
    "offline.message": "Проверьте подключение и попробуйте снова",
    "offline.retry": "Повторить",
    "settings.title": "Настройки",
    "settings.language": "Язык",
  },
  ko: {
    "app.name": "Know Deep",
    "app.tagline": "올인원 스마트 AI 동반자",
    "nav.features": "기능",
    "nav.tools": "도구",
    "nav.pricing": "가격",
    "nav.gallery": "갤러리",
    "nav.dashboard": "대시보드",
    "auth.signIn": "로그인",
    "auth.signUp": "회원가입",
    "auth.email": "이메일",
    "auth.password": "비밀번호",
    "auth.displayName": "표시 이름",
    "auth.country": "국가",
    "auth.language": "언어",
    "auth.welcome": "다시 오신 것을 환영합니다",
    "auth.createAccount": "계정 만들기",
    "auth.noAccount": "계정이 없으신가요? 회원가입",
    "auth.hasAccount": "이미 계정이 있으신가요? 로그인",
    "auth.logout": "로그아웃",
    "chat.placeholder": "메시지를 입력하세요...",
    "chat.send": "보내기",
    "chat.newChat": "새 채팅",
    "common.loading": "로딩 중...",
    "common.error": "오류",
    "common.success": "성공",
    "common.cancel": "취소",
    "common.save": "저장",
    "common.delete": "삭제",
    "common.edit": "편집",
    "common.search": "검색",
    "pricing.title": "플랜 선택",
    "pricing.month": "/월",
    "pricing.upgrade": "업그레이드",
    "offline.title": "인터넷 연결 없음",
    "offline.message": "연결을 확인하고 다시 시도하세요",
    "offline.retry": "다시 시도",
    "settings.title": "설정",
    "settings.language": "언어",
  },
  it: {
    "app.name": "Know Deep",
    "app.tagline": "Il tuo compagno AI intelligente tutto-in-uno",
    "nav.features": "Funzionalità",
    "nav.tools": "Strumenti",
    "nav.pricing": "Prezzi",
    "nav.gallery": "Galleria",
    "nav.dashboard": "Dashboard",
    "auth.signIn": "Accedi",
    "auth.signUp": "Registrati",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.displayName": "Nome visualizzato",
    "auth.country": "Paese",
    "auth.language": "Lingua",
    "auth.welcome": "Bentornato",
    "auth.createAccount": "Crea account",
    "auth.noAccount": "Non hai un account? Registrati",
    "auth.hasAccount": "Hai già un account? Accedi",
    "auth.logout": "Esci",
    "chat.placeholder": "Scrivi il tuo messaggio...",
    "chat.send": "Invia",
    "chat.newChat": "Nuova chat",
    "common.loading": "Caricamento...",
    "common.error": "Errore",
    "common.success": "Successo",
    "common.cancel": "Annulla",
    "common.save": "Salva",
    "common.delete": "Elimina",
    "common.edit": "Modifica",
    "common.search": "Cerca",
    "pricing.title": "Scegli il tuo piano",
    "pricing.month": "/mese",
    "pricing.upgrade": "Aggiorna",
    "offline.title": "Nessuna connessione Internet",
    "offline.message": "Verifica la connessione e riprova",
    "offline.retry": "Riprova",
    "settings.title": "Impostazioni",
    "settings.language": "Lingua",
  },
  gu: {
    "app.name": "Know Deep",
    "app.tagline": "તમારો ઓલ-ઇન-વન સ્માર્ટ AI સાથી",
    "nav.features": "લક્ષણો",
    "nav.tools": "સાધનો",
    "nav.pricing": "કિંમત",
    "nav.gallery": "ગેલેરી",
    "auth.signIn": "સાઇન ઇન કરો",
    "auth.signUp": "સાઇન અપ કરો",
    "auth.email": "ઇમેઇલ",
    "auth.password": "પાસવર્ડ",
    "auth.displayName": "પ્રદર્શન નામ",
    "auth.country": "દેશ",
    "auth.language": "ભાષા",
    "chat.placeholder": "તમારો સંદેશ ટાઇપ કરો...",
    "chat.send": "મોકલો",
    "common.loading": "લોડ થઈ રહ્યું છે...",
    "settings.language": "ભાષા",
  },
  kn: {
    "app.name": "Know Deep",
    "app.tagline": "ನಿಮ್ಮ ಆಲ್-ಇನ್-ಒನ್ ಸ್ಮಾರ್ಟ್ AI ಸಹಚರ",
    "nav.features": "ವೈಶಿಷ್ಟ್ಯಗಳು",
    "nav.tools": "ಪರಿಕರಗಳು",
    "nav.pricing": "ಬೆಲೆ",
    "nav.gallery": "ಗ್ಯಾಲರಿ",
    "auth.signIn": "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    "auth.signUp": "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    "auth.email": "ಇಮೇಲ್",
    "auth.password": "ಪಾಸ್‌ವರ್ಡ್",
    "auth.displayName": "ಪ್ರದರ್ಶನ ಹೆಸರು",
    "auth.country": "ದೇಶ",
    "auth.language": "ಭಾಷೆ",
    "chat.placeholder": "ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...",
    "chat.send": "ಕಳುಹಿಸಿ",
    "common.loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "settings.language": "ಭಾಷೆ",
  },
  ml: {
    "app.name": "Know Deep",
    "app.tagline": "നിങ്ങളുടെ ഓൾ-ഇൻ-വൺ സ്മാർട്ട് AI സഹായി",
    "nav.features": "സവിശേഷതകൾ",
    "nav.tools": "ഉപകരണങ്ങൾ",
    "nav.pricing": "വില",
    "nav.gallery": "ഗാലറി",
    "auth.signIn": "സൈൻ ഇൻ",
    "auth.signUp": "സൈൻ അപ്പ്",
    "auth.email": "ഇമെയിൽ",
    "auth.password": "പാസ്‌വേഡ്",
    "auth.displayName": "പ്രദർശന നാമം",
    "auth.country": "രാജ്യം",
    "auth.language": "ഭാഷ",
    "chat.placeholder": "നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...",
    "chat.send": "അയയ്ക്കുക",
    "common.loading": "ലോഡ് ചെയ്യുന്നു...",
    "settings.language": "ഭാഷ",
  },
  pa: {
    "app.name": "Know Deep",
    "app.tagline": "ਤੁਹਾਡਾ ਆਲ-ਇਨ-ਵਨ ਸਮਾਰਟ AI ਸਾਥੀ",
    "nav.features": "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    "nav.tools": "ਔਜ਼ਾਰ",
    "nav.pricing": "ਕੀਮਤ",
    "nav.gallery": "ਗੈਲਰੀ",
    "auth.signIn": "ਸਾਈਨ ਇਨ ਕਰੋ",
    "auth.signUp": "ਸਾਈਨ ਅੱਪ ਕਰੋ",
    "auth.email": "ਈਮੇਲ",
    "auth.password": "ਪਾਸਵਰਡ",
    "auth.displayName": "ਡਿਸਪਲੇ ਨਾਮ",
    "auth.country": "ਦੇਸ਼",
    "auth.language": "ਭਾਸ਼ਾ",
    "chat.placeholder": "ਆਪਣਾ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...",
    "chat.send": "ਭੇਜੋ",
    "common.loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    "settings.language": "ਭਾਸ਼ਾ",
  },
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem("app_language");
    return saved || "en";
  });

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    localStorage.setItem("app_language", lang);
  };

  const t = (key: string): string => {
    const langTranslations = translations[language] || translations.en;
    return langTranslations[key] || translations.en[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
    // Set RTL for Arabic
    if (language === "ar") {
      document.documentElement.dir = "rtl";
    } else {
      document.documentElement.dir = "ltr";
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
